sonar.projectKey=mlkareeb_cohort-9-java-12377-areeb
sonar.organization=mlkareeb

# --- SOURCE DIRECTORIES ---
# Only point to the frontend source folder here since the backend is handled entirely by Maven
sonar.sources=frontend/src
sonar.tests=frontend/src
sonar.test.inclusions=**/*.test.js,**/*.spec.js
sonar.exclusions=**/*.test.js,**/*.spec.js

# --- ENCODING ---
sonar.sourceEncoding=UTF-8